# Generated by Django 3.2.13 on 2022-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220616_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replying_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
